### ISSUE TITLE
Problem with AddTensorProductOnMorphisms

### ISSUE THREAD

**Issue by djuteau** [homalg-project/HeckeCategories#6]
There is a drawback is allowing any f in Q for a morphism between 2 different elements of W:
if we tensor two morphisms, one from x1 to x2, the other from y1 to y2, with x1 <> x2 and y1 <> y2, but x1y1 = x2y2, then we should return the 0 morphism, but the code below does not...

AddTensorProductOnMorphisms( Std,
      function( cat, mor1, mor2 )
        local phi_x;
        
        phi_x := UnderlyingTwistingRingMap( cat )( ObjectDatum( cat, Range( mor1 ) ) );
        
        return MorphismConstructor( cat,
                       TensorProductOnObjects( cat, Source( mor1 ), Source( mor2 ) ),
                       MorphismDatum( cat, mor1 ) * Pullback( phi_x, MorphismDatum( cat, mor2 ) ),
                       TensorProductOnObjects( cat, Range( mor1 ), Source( mor2 ) ) );
        
    end );

**Comment by mohamed-barakat** [comment]
`IsZero` should verify that the morphism is indeed zero, regardless of the view method.

**Comment by mohamed-barakat** [comment]
One can of course adapt the view method, but in this case, it will trigger a computation.

**Comment by djuteau** [comment]
I don't see the relation with the view method. My point is: in the arguments, the morphisms are congruent to zero because sources and targets differ; but in the tensor product, we have an endomorphism, with an arbitrary MorphismDatum!

**Comment by mohamed-barakat** [comment]
Ah, I see. This is a mathematical bug.

**Comment by mohamed-barakat** [comment]
A solution would be to normalize during the creation of the morphism.
